language: cpp

addons:
    apt:
        sources:
          - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
          - cmake
          - cmake-data

before_install:

install:
    ./prepare.sh travis

script:
    ./build.sh

cache:
    directories:
      - clang
      - boost