language: cpp

os:
  - osx

osx_image: xcode7.3

git:
    submodules: false
    depth: 3

addons:
    apt:
        sources:
          - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
          - cmake
          - cmake-data

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gcc-4.8 g++-4.8 -y ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8 ; fi
  - ./prepare.sh travis

install:

script:
    ./build.sh

cache:
    directories:
      - clang
      - boost
      - gtest
      - rocksdb