language: cpp

addons:
    apt:
        sources:
          - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
          - cmake
          - cmake-data

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.9 g++-4.9 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - ./prepare.sh travis

install:

script:
    ./build.sh

cache:
    directories:
      - clang
      - boost
      - gtest
      - rocksdb